{{- if eq .Values.workloadType "statefulset" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bss.fullname" . }}
  labels:
    {{- include "bss.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "bss.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bss.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bss.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bss.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "bss.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ coalesce ((.Values.global).image).tag .Values.image.tag .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.args }}
          args:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.probes }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- include "bss.env" . | nindent 10 }}
          {{- with .Values.environmentsFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.statefulset.volumeClaimTemplates }}
  volumeClaimTemplates:
  {{- range . }}
    - metadata:
        name: {{ .name }}
        labels:
          {{- include "bss.labels" $ | nindent 10 }}
          {{- with .labels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .accessModes }}
          - {{ . }}
          {{- end }}
        resources:
          requests:
            storage: {{ .storage }}
        {{- with .storageClassName }}
        storageClassName: {{ . | quote }}
        {{- end }}
        {{- with .selector }}
        selector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .volumeName }}
        volumeName: {{ . }}
        {{- end }}
        {{- with .volumeMode }}
        volumeMode: {{ . }}
        {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
