apiVersion: v1
entries:
  base-template:
  - apiVersion: v2
    appVersion: "2.5"
    created: "2022-10-27T18:35:08.306405527+03:00"
    description: A base Helm chart for Kubernetes
    digest: 46425ad04f4891b6af3606193c2ea074c24cf248dca1c9a5791a98c447f8b860
    name: base-template
    type: application
    urls:
    - https://yigitbasalma.github.io/helm-template/charts/template/base-template-0.1.0.tgz
    version: 0.1.0
generated: "2022-10-27T18:35:08.305305257+03:00"
